onboarding_page <- div(
  class = "ui onboarding page one column grid container dashboard hidden",
  style = "padding-top: 1em !important;",
  div(class = "sixteen wide column", h1("Onboarding")),
  content_box(
    "On-boarding to the new NHS Jobs service",
    label("Were you recently involved in the process of on-boarding"),
    fluidRow_2cols_toggle_B(highchartOutput, "involved_onboarding"),
    label("Have you answered questions about your on-boarding experi"),
    fluidRow_2cols_toggle_B(highchartOutput, "answered_qs_onboarding"),
    label("Did the transition to the new service meet all of your on"),
    fluidRow_2cols_toggle_B(highchartOutput, "transition_reqs_met"),
    label("Please tell us about the on-boarding requirements that we"),
    user_group_select("transition_reqs_not_met_comment_group"),
    fluidRow_2cols_toggle_B(dataTableOutput, "transition_reqs_not_met_comment"),
    label("Were all of your queries fully resolved?"),
    fluidRow_2cols_toggle_B(highchartOutput, "contact_resolved"),
    label("Please tell us about your query and why it was not fully"),
    user_group_select("contact_not_resolved_comment_group"),
    fluidRow_2cols_toggle_B(dataTableOutput, "contact_not_resolved_comment"),
    label("Was the support team available at the time/s you needed s"),
    fluidRow_2cols_toggle_B(highchartOutput, "contact_available"),
    label("Was this because"),
    fluidRow_2cols_toggle_B(plotlyOutput, "contact_not_available_option"),
    label("Please tell us why the support team wasn't available."),
    user_group_select("contact_not_available_other_comment_group"),
    fluidRow_2cols_toggle_B(dataTableOutput, "contact_not_available_other_comment"),
    label("How easy was it to get the help you needed when you conta"),
    fluidRow_2cols_toggle_B(plotlyOutput, "contact_how_easy_rating"),
    label("Reasons for rating"),
    user_group_select("contact_how_easy_rating_comment_group"),
    fluidRow_2cols_toggle_B(dataTableOutput, "contact_how_easy_rating_comment"),
    label("Contact ratings"),
    aspect_radio_select("contact_aspects_rating_radio", contact_aspects_rating_choices),
    fluidRow_2cols_toggle_B(plotlyOutput, "contact_aspects_rating"),
  ),
  content_box(
    "The onboarding form",
    label("Onboarding ratings"),
    aspect_radio_select("onboarding_aspects_rating_radio", onboarding_aspects_rating_choices),
    fluidRow_2cols_toggle_B(plotlyOutput, "onboarding_aspects_rating"),
    label("Reasons for rating"),
    user_group_select("onboarding_aspects_comment_group"),
    fluidRow_2cols_toggle_B(dataTableOutput, "onboarding_aspects_comment"),
    label("Other contact"),
    user_group_select("contact_other_comment_group"),
    fluidRow_2cols_toggle_B(dataTableOutput, "contact_other_comment"),
    label("How many times did you contact us to resolve your query?"),
    fluidRow_2cols_toggle_B(plotlyOutput, "contact_instances"),
  ),
  content_box(
    "Setting up your new NHS Jobs account",
    label("Did you face any challenges when setting up your account"),
    fluidRow_2cols_toggle_B(plotlyOutput, "challenge_option"),
    label("Please tell us about the other challenges you faced when"),
    user_group_select("challenge_other_comment_group"),
    fluidRow_2cols_toggle_B(dataTableOutput, "challenge_other_comment"),
    label("Did the communications contain all the information you ne"),
    fluidRow_2cols_toggle_B(highchartOutput, "comms_reqs_met"),
    label("Please tell us what information you felt was missing."),
    user_group_select("comms_reqs_not_met_comment_group"),
    fluidRow_2cols_toggle_B(dataTableOutput, "comms_reqs_not_met_comment"),
  ),
  content_box(
    "Contacting the NHS Jobs on-boarding support team",
    label("Did you contact the NHS Jobs support team during your on-"),
    fluidRow_2cols_toggle_B(highchartOutput, "contact"),
    label("Thinking about your last contact, how did you get in touc"),
    fluidRow_2cols_toggle_B(plotlyOutput, "contact_option"),
  ),
  content_box(
    "Communications",
    label("Communication ratings"),
    aspect_radio_select("comms_aspects_rating_radio", comms_aspects_rating_choices),
    fluidRow_2cols_toggle_B(plotlyOutput, "comms_aspects_rating"),
    label("Did you feel you received the right amount of communicati"),
    fluidRow_2cols_toggle_B(highchartOutput, "comms_right_amount"),
  ),
  content_box(
    "Improvements and other feedback",
    label("What one thing would you suggest to improve the overall o"),
    user_group_select("would_improve_onboarding_comment_group"),
    fluidRow_2cols_toggle_B(dataTableOutput, "would_improve_onboarding_comment"),
    label("Do you have any other feedback on your on-boarding experi"),
    user_group_select("feedback_onboarding_comment_group"),
    fluidRow_2cols_toggle_B(dataTableOutput, "feedback_onboarding_comment"),
  ),
  content_box(
    "Overall satisfaction",
    label("NA"),
    fluidRow_2cols_toggle_B(highchartOutput, "nps_onboarding"),
    label("How easy was it to complete the on-boarding process overa"),
    fluidRow_2cols_toggle_B(highchartOutput, "nes_onboarding"),
  ),
  htmlOutput("onboardingtrigger")
)
